os.loadAPI("/apis/graphix")
graphix.bgColor(colors.lightBlue)
graphix.center(1,"MCOS Beta "..version)
graphix.center(2,"Coded by: datcoder1208")
graphix.center(3,"This code is copyrighed.")
graphix.center(5,"Credits:")
graphix.center(7,"Gonow32 for File Manager")
graphix.center(9,"GravityScore for SHA256 API")
graphix.center(11,"Thank you for using MCOS Beta "..version.."!")
sleep(5)
shell.run("/MCOS/desktop")
